name: GitHub Actions Update Repo
run-name: Updating repo file 🚀
on:
  schedule:
    - cron: "46 2 * * *"
jobs:
  Update-Repo:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - run: |
          pip install -r requirements.txt
          python update_repo.py
      - uses: stefanzweifel/git-auto-commit-action@v4
