name: GitHub Actions Update Repo
run-name: Updating repo file 🚀
on: [push]
#  schedule:
#    - cron: "2 46 * * *"
jobs:
  Update-Repo:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - run: |
          pip install -r requirements.txt
          python update_repo.py
      - run: |
          git add repo.xml
          git commit -m "update repo"
          git push